### PR TITLE
Readability edits

### PR DESCRIPTION
**Pull request by nmai**
You're very welcome!

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Such improvement, much wow

**Comment by nmai** [comment]
Yeah well I had to pick up the slack while you've been gone.

**Comment by skorezore** [comment]
Nick is such a valuable member of this team.

**Comment by nabijaczleweli** [comment]
I am very honoured to be a member of such a valuable team

**Comment by nmai** [comment]
Consider yourself blessed

**Pull request merged**
